Repository Cypherock/cysync-desktop, pull requests merged in 2022-08, with the labels that each got.

#172 CSI-1210: Allow the user to fetch logs even if the device connection is blocked
  cysync/src/constants/i18n/en.ts
  cysync/src/store/hooks/flows/useLogFetcher.ts
  cysync/src/store/provider/feedbackProvider.tsx
Labels: ready-to-merge

#169 PRD-1078 fix doubling of coin allocation
  cysync/src/pages/mainApp/sidebar/portfolio/charts/LineChart.tsx
  cysync/src/store/hooks/usePortfolio.ts
Labels: ready-to-merge

#189 PRD-1007 Show device is busy while updating
  cysync/src/pages/initialApp/deviceFlow/deviceSetup/stepperFormComponents/upgradingDevice.tsx
  cysync/src/pages/mainApp/deviceUpdater/initialFlow/stepperFormComponents/upgradingDevice.tsx
  cysync/src/pages/mainApp/sidebar/settings/tabViews/deviceHealth/deviceAuth.tsx
  cysync/src/store/provider/feedbackProvider.tsx
Labels: re-review needed

#194 CSI-1225: internet connection check before opening add coin flow from…
  cysync/src/pages/mainApp/sidebar/wallet/addWallet/index.tsx
Labels: ready-to-merge

#192 Handle com port errors
  cysync/src/errors/helpers.ts
  cysync/src/utils/errorHandler.ts
Labels: ready-to-merge

#183 CSI-1222: Fix condition for Retry Device connection after device auth
  cysync/src/store/hooks/flows/useDeviceAuth.ts
Labels: ready-to-merge

#193 CSI-1231: Abort flows after locking in initial app
  cysync/src/pages/ExitCleanup.tsx
  cysync/src/store/provider/lockscreenProvider.tsx
Labels: ready-to-merge

#195 CSI-1216: Enable Accept T&C only after scrolling to the bottom
  cysync/src/pages/initialApp/deviceFlow/TermsAndUse.tsx
Labels: ready-to-merge

#212 CSI-1254: Show loading indicator while calculating max send amount
  cysync/src/pages/mainApp/sidebar/wallet/send/formComponents/Input.tsx
  cysync/src/pages/mainApp/sidebar/wallet/send/formStepComponents/Recipient.tsx
  cysync/src/pages/mainApp/sidebar/wallet/send/stepperForm.tsx
  cysync/src/store/hooks/flows/useSendTransaction.ts
Labels: resolve conflict
